version: '3.7'

services:
  ####
  # ELK stack
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
  elasticsearch:
    build: elasticsearch/
  logstash:
    build: logstash/
  filebeat:
    build: filebeat/
    volumes:
      - "nginx-logvolume:/var/log/share/nginx"
      - "java-logvolume:/var/log/share/java"
  ####
  # infrastructure services
  nginx:
    build: nginx/
    volumes:
      - "nginx-logvolume:/var/log/nginx"
    ports:
      - "80:80"
  haproxy:
    build: haproxy/
    extra_hosts:
      - "internal:172.17.0.1"
  ####
  # application services
  eureka:
    build: eureka/
    volumes:
      - "java-logvolume:/var/log"
  gateway:
    build: gateway/
    volumes:
      - "java-logvolume:/var/log"
  account:
    build: account/
    volumes:
      - "java-logvolume:/var/log"
    depends_on:
      - eureka
      - haproxy

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  nginx-logvolume:
  java-logvolume:
