logging.metrics:
  enabled: false

filebeat.inputs:
  - type: log
    tags: ['log', 'java']
    multiline:
      pattern: '^\d{4}\-\d{2}\-\d{2}(\s+|T)\d{2}\:\d{2}\:\d{2}(\.|\,)\d{3}\s+(TRACE|DEBUG|NOTICE|INFO|WARN|ERROR|FATAL)'
      negate: true
      match: after
    paths:
      - "/var/log/share/*.log"

output.logstash:
  hosts: ["logstash:5044"]
